export default {
    'Bryn Bliska': 'https://www.brynbliska.com/',
    'DNA Labs': 'https://www.dnalabssoftware.com/',
    'Josh Mobley Music': 'https://www.joshmobley.com/',
    'Kickback Couture': 'https://kickbackcouture.com/',
    'Lab One Recordings': 'https://lab-one-recordings.co.uk/',
    'Melodiefabriek': 'https://melodiefabriek.com/',
    'ModeAudio': 'https://modeaudio.com/',
    'New Loops': 'https://newloops.com/',
    'Paul Ortiz': 'https://paulortiz.bandcamp.com/',
    'Quixotic Sound Design': 'https://www.quixoticsounddesign.com/',
    'Reasonistas': 'https://www.reasonistas.com/',
    'Reverb Machine': 'https://reverbmachine.com/',
    'Seán Murray': 'https://www.seanmurrayguitar.com/',
    'SKP Sound Design': 'https://www.skpsounds.com/',
    'Theodora Flygt': 'https://soundcloud.com/theodora49',
    'Tobtok': 'https://soundcloud.com/tobtok',
    'Undrgrnd Sounds': 'https://www.undrgrndsounds.com/',
    'Venus Theory': 'https://venustheory.com/',
};